# the following block is needed for the shared Docker-based runner
image: docker:git
variables:
  DOCKER_DRIVER: "overlay" # recommended for docker-in-docker
services:
  - docker:dind # enable docker-in-docker
before_script:
  - apk add --update bash coreutils # install travis depedencies
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
kinetic:
  script: 
    - .ci_config/gitlab.sh
  variables:
    ROS_DISTRO: "kinetic"
  tags:
    - docker-in-docker

# image: ros:kinetic-ros-core

# variables:
#   ROS_PACKAGES_TO_INSTALL: ""
#   USE_ROSDEP: "true"
# 
# cache:
#   paths:
#     - ccache/
# 
# before_script:
#  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
#  - source ros_gitlab_ci/gitlab-ci.bash
# 
# catkin_make:
#   stage: build
#   script:
#     - catkin_make
# 
# catkin_build:
#   stage: build
#   script:
#     - catkin build --summarize --no-status --force-color

