test:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install nose
  # NOTE: Installing these packages by hand is a
  # temporary solution.
  # TODO: Try setting up a runner with a ROS image.
  - pip install pyyaml
  - pip install jinja2
  - nosetests test/executive_smach_tutorials.py
