test_python2:
  image: python:2.7
  script:
    - "# Test with python 2"
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install virtualenv
    - virtualenv --system-site-packages --python=/usr/bin/python2 venv2
    - venv2/bin/pip install nose
    - venv2/bin/pip install ruamel.yaml
    - venv2/bin/pip install jinja2
    - venv2/bin/nosetests test/executive_smach_tutorials_test.py
    - venv2/bin/nosetests test/smacha_test_examples.py
  tags:
    - docker
    - python2

test_python3:
  image: python:3.5
  script:
    - "# Test with python 3"
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip install virtualenv
    - virtualenv --system-site-packages --python=/usr/bin/python3 venv3
    - venv3/bin/pip install nose
    - venv3/bin/pip install ruamel.yaml
    - venv3/bin/pip install jinja2
    - venv3/bin/nosetests test/executive_smach_tutorials_test.py
    - venv3/bin/nosetests test/smacha_test_examples.py
  tags:
    - docker
    - python3
