test_python2:
  image: python:2.7
  script:
    - "# Test with python 2"
    - pip install virtualenv
    - virtualenv --system-site-packages --python=/usr/bin/python2 venv2
    - venv2/bin/pip install nose
    - venv2/bin/pip install pyyaml
    - venv2/bin/pip install jinja2
    - venv2/bin/nosetests test/executive_smach_tutorials.py
  tags:
    - docker
    - python2

test_python3:
  image: python:3.5
  script:
    - "# Test with python 3"
    - pip install virtualenv
    - virtualenv --system-site-packages --python=/usr/bin/python3 venv3
    - venv3/bin/pip install nose
    - venv3/bin/pip install pyyaml
    - venv3/bin/pip install jinja2
    - venv3/bin/nosetests test/executive_smach_tutorials.py
  tags:
    - docker
    - python3
