# the following block is needed for the shared Docker-based runner
image: docker:git
variables:
  DOCKER_DRIVER: "overlay" # recommended for docker-in-docker
services:
  - docker:dind # enable docker-in-docker
before_script:
  - apk add --update bash coreutils tar # install travis depedencies
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci_config
# Build config for gitlab.com
kinetic:
  only:
    variables:
      - $CI_PROJECT_URL == "https://gitlab.com/reconcell/smacha"
  script: 
    - .ci_config/gitlab.sh
  variables:
    ROS_DISTRO: "kinetic"
    CI_DEBUG_TRACE: "true"
# Build config for repo.ijs.si
kinetic:
  only:
    variables:
      - $CI_PROJECT_URL == "https://repo.ijs.si/reconcell/smacha"
  tags:
    - reconcell
  script: 
    - .ci_config/gitlab.sh
  variables:
    ROS_DISTRO: "kinetic"
    CI_DEBUG_TRACE: "true"
